name: 'Display JSON values'
description: 'Display JSON values in your actions'
author: 'Guilherme Scaldelai'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The repository name'
    required: true
  pr_number:
    description: 'The number of the pull request'
    required: true
  token:
    description: 'The Github token to access Github API'
  file:
    description: 'JSON file to read the values'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
