name: 'Display JSON values'
description: 'Display JSON values in your actions'
author: 'Guilherme Scaldelai'
inputs:
  file:
    description: 'JSON file to read the values'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
