name: 'Display JSON values'
description: 'Display JSON values in your actions'
inputs:
  json-value:
    description: 'JSON values to be displayed'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
